language: python
sudo: false
cache: pip
env:
  global:
    MOZ_HEADLESS=1
matrix:
  include:
    - python: 2.7
      env: TOXENV=py27-dj111
    - python: 3.4
      env: TOXENV=py34-dj111
    - python: 3.4
      env: TOXENV=py34-dj20
    - python: 3.5
      env: TOXENV=py35-dj111
    - python: 3.5
      env: TOXENV=py35-dj20
    - python: 3.5
      env: TOXENV=py35-dj21
    - python: 3.6
      env: TOXENV=py36-dj111
    - python: 3.6
      env: TOXENV=py36-dj20
    - python: 3.6
      env: TOXENV=py36-dj21
    - python: 3.6
      env: TOXENV=py36-djdev

  allow_failures:
    - env: TOXENV=py34-djdev
    - env: TOXENV=py36-djdev
# before_install:
#   - wget https://github.com/mozilla/geckodriver/releases/download/v0.19.1/geckodriver-v0.19.1-linux64.tar.gz
#   - mkdir geckodriver
#   - tar -xzf geckodriver-v0.19.1-linux64.tar.gz -C geckodriver
#   - export PATH=$PATH:$PWD/geckodriver
install:
  - pip install tox
# addons:
#   #firefox: "48.0.2"
#   firefox: latest

# before_script:
#   - export DJANGO_LIVE_TEST_SERVER_ADDRESS=localhost:8000-8010,8080,9200-9300
#   - export DJANGO_TEST_PROCESSES=1
#   - export DISPLAY=:99.0
#   - sh -e /etc/init.d/xvfb start
#   #- python manage.py runserver &
#   #- sleep 3 # give django server time to bind to sockets
#   - sleep 3 # give xvfb some time to start
#   # - rackup  # start a Web server
#   # - sleep 3 # give Web server some time to bind to sockets, etc

script:
  - tox -v

#after_success:
#  - coverage combine
#  - codecov
